version: '3'

networks:
  atlas-net:
    driver: bridge

services:
  app:
    build: .
    container_name: atlas-auth
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
      - redis
    working_dir: /usr/app/
    networks:
      - atlas-net
    ports: 
      - ${API_PORT}:${API_PORT}

  database:
    image: postgres:latest
    container_name: pgdb-auth
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    networks:
      - atlas-net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: redis-auth
    restart: always
    networks:
      - atlas-net
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redisdata:/data/redis

volumes:
  data:
    driver: local
  redisdata:
    driver: local